# Generated by Django 4.2.6 on 2024-03-30 06:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('args', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.JSONField(null=django.db.models.deletion.CASCADE)),
                ('asyncro', models.BooleanField(default=False)),
                ('job_id', models.CharField(default=uuid.UUID('c7ef7ebf-dd60-480e-a21e-c17476e77b05'), max_length=40)),
                ('interval_number', models.IntegerField(default=1)),
                ('interval', models.CharField(max_length=20)),
                ('at', models.CharField(max_length=5, null=True)),
                ('run_once', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command.function')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.JSONField(null=True)),
                ('executed', models.BooleanField(default=False)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('asyncro', models.BooleanField(default=False)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='command.function')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='command.scheduledcommand')),
            ],
        ),
    ]
