# Generated by Django 4.2.6 on 2024-03-30 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('629c10a9-ec28-4f3e-835f-d12726978518'), max_length=40),
        ),
    ]
