# Generated by Django 4.2.6 on 2024-03-30 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0002_alter_scheduledcommand_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('8ff24b41-b3ad-4a1f-8304-2be792673d9d'), max_length=40),
        ),
    ]
