# Generated by Django 4.2.6 on 2024-03-30 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0004_alter_scheduledcommand_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('da9661fa-7dff-4401-abdb-5367b8fed92d'), max_length=40),
        ),
    ]
