# Generated by Django 4.2.6 on 2024-03-30 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0005_alter_scheduledcommand_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('3680be9d-1370-4cc7-9159-f2a80a10e997'), max_length=40),
        ),
    ]
