# Generated by Django 4.2.6 on 2024-03-30 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0006_alter_scheduledcommand_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('53760fa7-1654-43f4-95ae-aa20cea8632a'), max_length=40),
        ),
    ]
