# Generated by Django 4.2.6 on 2024-03-30 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0007_alter_scheduledcommand_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('93dff247-2718-4bd5-a0d4-8943d452d996'), max_length=40),
        ),
    ]
