# Generated by Django 4.2.6 on 2024-03-30 06:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0008_alter_scheduledcommand_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='function',
            name='remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('e641d45b-69db-4f89-952b-2de475027d9a'), max_length=40),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('device_id', models.UUIDField(default=uuid.UUID('57cc5ae7-a04e-43b9-845c-0cf5583c1848'), unique=True)),
                ('device_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='command.devicetype')),
            ],
        ),
        migrations.AddField(
            model_name='function',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='command.device'),
        ),
    ]
