# Generated by Django 4.2.6 on 2024-03-30 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0009_devicetype_function_remote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('80dcdbf9-a27b-4e4d-bb4a-f49fa6f1fbaa'), unique=True),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('f8941a6d-2f4f-42bf-b684-6134fc5e84c4'), max_length=40),
        ),
    ]
