# Generated by Django 4.2.6 on 2024-03-30 07:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0012_alter_device_device_id_alter_scheduledcommand_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('f863f895-5b66-4396-9652-a0698c68fc93'), unique=True),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('1d6e2845-a9e2-48a8-8194-0f85cc2222bb'), max_length=40),
        ),
    ]
