# Generated by Django 4.2.6 on 2024-03-30 21:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0013_alter_device_device_id_alter_scheduledcommand_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('153545f5-7ba3-43dd-8390-3204ad7ea75f'), unique=True),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('3b506fea-5982-4bb3-9625-769568d62ae2'), max_length=40),
        ),
    ]
