# Generated by Django 4.2.6 on 2024-03-30 21:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0014_alter_device_device_id_alter_scheduledcommand_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('3913c1dd-e7fc-4d3e-874c-11e24858dfa8'), unique=True),
        ),
        migrations.AlterField(
            model_name='function',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='command.device'),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('3603bc51-463c-441f-b9ec-fca70ec97313'), max_length=40),
        ),
    ]
