# Generated by Django 4.2.6 on 2024-03-30 22:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0016_alter_device_device_id_alter_scheduledcommand_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('4a720869-5c07-4e0b-b358-e468e16a5f7a'), unique=True),
        ),
        migrations.AlterField(
            model_name='function',
            name='args',
            field=models.JSONField(default=[], null=True),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('b4a81cfa-ed8c-441d-96ab-659d05624f32'), max_length=40),
        ),
    ]
