# Generated by Django 4.2.6 on 2024-03-30 22:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0018_alter_device_device_id_alter_function_args_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('e36bd707-6d7f-4ee6-8882-9fc3e86aa0da'), unique=True),
        ),
        migrations.AlterField(
            model_name='function',
            name='args',
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('866754f5-a230-4cbd-b143-9b6a122299c8'), max_length=40),
        ),
    ]
