# Generated by Django 4.2.6 on 2024-03-31 06:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0019_alter_device_device_id_alter_function_args_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='scheduledcommand',
            name='job_id',
            field=models.CharField(default=uuid.UUID('e0fa2193-c9d8-402c-8656-1f9f6031d5a6'), max_length=40),
        ),
    ]
