# Generated by Django 4.2.6 on 2024-04-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0021_alter_scheduledcommand_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='asyncro',
        ),
        migrations.AddField(
            model_name='function',
            name='asycnro',
            field=models.BooleanField(default=False),
        ),
    ]
