# Generated by Django 4.2.6 on 2024-04-02 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0022_remove_command_asyncro_function_asycnro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='asycnro',
            new_name='asyncro',
        ),
    ]
