# Generated by Django 4.2.6 on 2024-04-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0023_rename_asycnro_function_asyncro'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='return_message',
            field=models.JSONField(null=True),
        ),
    ]
