# Generated by Django 4.2.6 on 2024-04-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0024_command_return_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='function',
            unique_together={('name', 'device')},
        ),
    ]
