# Generated by Django 4.2.6 on 2024-04-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0026_function_response_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
