# Generated by Django 4.2.6 on 2024-04-17 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0027_function_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='command.device'),
        ),
    ]
