# Generated by Django 4.2.6 on 2024-04-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0028_alter_function_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='read_write',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Read'), (2, 'Write')], default=0),
        ),
    ]
