# Generated by Django 4.2.6 on 2024-06-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0029_function_read_write'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_itself',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
