# Generated by Django 4.2.6 on 2024-06-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0030_device_is_itself_alter_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
