# Generated by Django 4.2.6 on 2023-11-16 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='MqttServer',
            fields=[
                ('server_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.server')),
                ('protocol', models.CharField(choices=[('MQTT', 'mqtt'), ('MQTTS', 'mqtts'), ('WS', 'ws'), ('WSS', 'ws')], default='MQTTS')),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=8883)),
                ('path', models.CharField(default='/mqtt', max_length=25)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('ssl', models.BooleanField(default=True)),
            ],
            bases=('automation.server',),
        ),
    ]
