# Generated by Django 4.2.6 on 2023-11-27 05:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_dataentry_datagroup_dataitem_device_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('c4c1ad0b-3dfa-4046-859a-7c9e61388f8e'), unique=True),
        ),
    ]
