# Generated by Django 4.2.6 on 2023-11-27 05:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_alter_device_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataitem',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('d5aa17f9-2fcd-4217-a5cd-1cce6ddc4e4d'), unique=True),
        ),
    ]
