# Generated by Django 4.2.6 on 2023-11-27 06:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_remove_devicetype_devices_device_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('4e0e8b00-7d75-47c5-b876-d886c1a9329e'), unique=True),
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.devicetype'),
        ),
    ]
