# Generated by Django 4.2.6 on 2023-11-27 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_alter_device_device_id_remove_device_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('2de37f0c-d80e-44cc-8218-396af40f257d'), unique=True),
        ),
    ]
