# Generated by Django 4.2.6 on 2023-11-27 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_alter_device_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('ba840bd0-4f41-42b3-9add-9666e35d992a'), unique=True),
        ),
    ]
