# Generated by Django 4.2.6 on 2023-11-27 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_alter_device_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('83eb1cb3-15e2-4b0d-8078-d364d84aa80e'), unique=True),
        ),
    ]
