# Generated by Django 4.2.6 on 2023-11-27 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0011_alter_device_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('33cc3f9e-8bce-4b63-b595-258909a42b2a'), unique=True),
        ),
    ]
