# Generated by Django 4.2.6 on 2023-11-27 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_alter_device_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataitem',
            name='data_group',
            field=models.ManyToManyField(null=True, to='automation.datagroup'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('d3052a05-a359-4068-85b5-9e69dde0ef7a'), unique=True),
        ),
    ]
