# Generated by Django 4.2.6 on 2023-11-27 06:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0014_alter_device_device_id_alter_device_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataitem',
            name='data_group',
            field=models.ManyToManyField(blank=True, to='automation.datagroup'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('93c11125-6e5a-409b-930a-aa3186f3ecb2'), unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.devicetype'),
        ),
    ]
