# Generated by Django 4.2.6 on 2023-11-27 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_restserver_server_server_type_alter_device_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('fc287238-f6c6-40ce-8f90-ad50ceba4056'), unique=True),
        ),
        migrations.AlterField(
            model_name='restserver',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restserver',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
