# Generated by Django 4.2.6 on 2023-11-27 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0017_alter_device_device_id_alter_restserver_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('b9bf167a-bfc0-483c-bd45-e08f9884ff1c'), unique=True),
        ),
        migrations.AlterField(
            model_name='restserver',
            name='path',
            field=models.CharField(default='/apis', max_length=25),
        ),
    ]
