# Generated by Django 4.2.6 on 2023-11-28 05:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0019_alter_device_device_id_alter_restserver_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('b8c4b905-472d-4005-bff7-c76bee554193'), unique=True),
        ),
    ]
