# Generated by Django 4.2.6 on 2023-11-28 06:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0020_alter_device_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('dd1d204c-abdd-4b62-be73-6485b23aad75'), unique=True),
        ),
    ]
