# Generated by Django 4.2.6 on 2023-11-28 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0022_realdataitem_logging_deadband_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realdataentry',
            name='decimal_places',
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('de48a0d1-a375-419d-b729-b0809a8f2363'), unique=True),
        ),
    ]
