# Generated by Django 4.2.6 on 2023-11-30 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0023_remove_realdataentry_decimal_places_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogLoggingMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logging_on', models.BooleanField(default=False)),
                ('logging_deadband', models.FloatField(default=1.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoggingMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loggin_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='realdataitem',
            old_name='hi_scale',
            new_name='raw_hi',
        ),
        migrations.RenameField(
            model_name='realdataitem',
            old_name='lo_scale',
            new_name='raw_lo',
        ),
        migrations.RemoveField(
            model_name='integerdataitem',
            name='hi_scale',
        ),
        migrations.RemoveField(
            model_name='integerdataitem',
            name='lo_scale',
        ),
        migrations.RemoveField(
            model_name='realdataitem',
            name='logging_deadband',
        ),
        migrations.RemoveField(
            model_name='realdataitem',
            name='logging_on',
        ),
        migrations.AddField(
            model_name='integerdataitem',
            name='raw_hi',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='integerdataitem',
            name='raw_lo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='integerdataitem',
            name='scale_hi',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='integerdataitem',
            name='scale_lo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='realdataitem',
            name='scale_hi',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='realdataitem',
            name='scale_lo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('10b1b4f7-9f25-42ca-b17c-e1b25bac2d97'), unique=True),
        ),
        migrations.AlterField(
            model_name='integerdataitem',
            name='scaling_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realdataitem',
            name='scaling_on',
            field=models.BooleanField(default=False),
        ),
    ]
