# Generated by Django 4.2.6 on 2023-11-30 08:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0024_analogloggingmixin_loggingmixin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalogLoggingMixin',
        ),
        migrations.DeleteModel(
            name='LoggingMixin',
        ),
        migrations.AddField(
            model_name='discretedataitem',
            name='logging_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='integerdataitem',
            name='logging_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realdataitem',
            name='logging_deadband',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='realdataitem',
            name='logging_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stringdataitem',
            name='logging_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('198cceff-7013-41fe-987e-f457add6587e'), unique=True),
        ),
    ]
