# Generated by Django 4.2.6 on 2023-11-30 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0025_delete_analogloggingmixin_delete_loggingmixin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realdataentry',
            name='value_raw',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('ef97821b-0402-4b00-9317-9e75c12b2055'), unique=True),
        ),
        migrations.AlterField(
            model_name='realdataentry',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
