# Generated by Django 4.2.6 on 2024-03-29 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0026_realdataentry_value_raw_alter_device_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('9bd9c4be-a2e5-4b49-bff5-cb8fd32cf8a3'), unique=True),
        ),
    ]
