# Generated by Django 4.2.6 on 2024-03-29 05:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0027_topic_active_alter_device_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataitem',
            name='read_write',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Read'), (2, 'Write'), (3, 'Read Write')], default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('f84ca20c-c6c2-4b1a-a4d0-8ac3fc964a64'), unique=True),
        ),
    ]
