# Generated by Django 4.2.6 on 2024-03-30 06:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0030_functionassigner_remove_dataitem_read_write_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('7f1734fa-ca88-4d75-a100-46b0bf52fc74'), unique=True),
        ),
    ]
