# Generated by Django 4.2.6 on 2024-03-30 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0032_alter_device_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('20232626-22c5-47ec-8d4f-5f962aeb1b27'), unique=True),
        ),
    ]
