# Generated by Django 4.2.6 on 2024-03-30 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0033_alter_device_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('f3abb1de-4db1-4750-b5cf-72ab4133a90a'), unique=True),
        ),
    ]
