# Generated by Django 4.2.6 on 2024-03-30 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0034_alter_device_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('6b805d68-28ee-4105-a22d-860421eff7ba'), unique=True),
        ),
    ]
