# Generated by Django 4.2.6 on 2024-03-30 06:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0035_alter_device_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionassigner',
            name='test',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('b6e21e7d-21fd-41f1-969e-90d5accd1535'), unique=True),
        ),
    ]
