# Generated by Django 4.2.6 on 2024-03-30 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0037_alter_dataitem_device_delete_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataitem',
            name='device',
        ),
    ]
